services:
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  keydrive:
    image: ghcr.io/keydrive/keydrive:edge
    ports:
      - 5555:5555
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
