name: Build KeyDrive

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created


jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: library/postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - run: yarn --version
      - run: go version
      - run: docker --version
      - name: Install Yarn Dependencies
        run: yarn --cwd web install --frozen-lockfile
      - name: Run Frontend Linting
        run: yarn --cwd web lint -f json -o eslint-report.json || true
      - name: Run React Tests
        run: yarn --cwd web test --ci --coverage --reporters=default --reporters=jest-junit
      - name: Build Frontend
        run: yarn --cwd web build
      - name: Install go dependencies
        run: go get -u github.com/jstemmer/go-junit-report
      - name: Run Backend Tests
        run: POSTGRES_HOST=postgres go test -v -coverprofile=coverage.out ./... 2>&1 | go-junit-report > junit.xml
