name: Build KeyDrive

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  test_react:
    name: Test Frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: 'web/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('web/yarn.lock') }}
      - name: Install Yarn Dependencies
        run: yarn --cwd web install --frozen-lockfile
      - name: Run Frontend Linting
        run: yarn --cwd web lint -f json -o eslint-report.json || true
      - name: Run React Tests
        run: yarn --cwd web test --ci --coverage --reporters=default --reporters=jest-junit
  build_react:
    name: Build Frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: 'web/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('web/yarn.lock') }}
      - name: Install Yarn Dependencies
        run: yarn --cwd web install --frozen-lockfile
      - name: Build Frontend
        run: yarn --cwd web build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: web/build
  test_go:
    name: Test Backend
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: library/postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install go dependencies
        run: go get -u github.com/jstemmer/go-junit-report
      - name: Run Backend Tests
        run: POSTGRES_HOST=postgres go test -v -coverprofile=coverage.out ./... 2>&1 | go-junit-report > junit.xml
  build_go:
    needs:
      - build_react
    name: Build Backend
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64
            goopts: GOOS=linux GOARCH=amd64
            target: linux/amd64
          - name: linux-armv6
            goopts: GOOS=linux GOARCH=arm GOARM=6
            target: linux/arm/v6
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
      - run: mkdir -p ${{ matrix.target }}
      - run: ${{ matrix.goopts }} go build -o ${{ matrix.target }}/keydrive ./main.go
      - run: chmod +x ${{ matrix.target }}/keydrive
      - uses: actions/upload-artifact@v2
        with:
          name: binary-${{ matrix.name }}
          path: ${{ matrix.target }}
  build_docker:
    needs:
      - build_go
    name: Build Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Determine branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Determine tag name
        run: if [ $BRANCH_NAME == "main" ]; then echo "TAG_NAME=preview" >> $GITHUB_ENV; else echo "TAG_NAME=$BRANCH_NAME" >> $GITHUB_ENV; fi;
      - uses: actions/download-artifact@v2
        with:
          name: binary-linux-x64
      - uses: actions/download-artifact@v2
        with:
          name: binary-linux-armv6
      - uses: docker/build-push-action@v2
        with:
          context: .false
          platforms: linux/amd64,linux/arm/v6
          push: true
          tags: ghcr.io/keydrive/keydrive:${{ env.TAG_NAME }}