name: Build KeyDrive

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  test_react:
    name: Test Frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/cache@v2
        with:
          path: 'web/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('web/yarn.lock') }}
      - name: Install Yarn Dependencies
        run: yarn --cwd web install --frozen-lockfile
      - name: Run Frontend Linting
        run: yarn --cwd web lint -f json -o eslint-report.json || true
      - name: Run React Tests
        run: yarn --cwd web test --ci --coverage --reporters=default --reporters=jest-junit
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'web/junit.xml'
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-tests
          path: |
            web/coverage/lcov.info
            web/eslint-report.json
            web/junit.xml
  test_go:
    name: Test Backend
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.20'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install go dependencies
        run: go get -u github.com/jstemmer/go-junit-report
      - name: Run Backend Tests
        run: go test -v -coverprofile=coverage.out ./... 2>&1 | go-junit-report > junit.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'junit.xml'
      - uses: actions/upload-artifact@v2
        with:
          name: backend-tests
          path: |
            coverage.out
            junit.xml
  sonar_analysis:
    name: SonarCloud Analysis
    needs:
      - test_go
      - test_react
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: frontend-tests
          path: web
      - uses: actions/download-artifact@v2
        with:
          name: backend-tests
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
  build_react:
    name: Build Frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/cache@v2
        with:
          path: 'web/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('web/yarn.lock') }}
      - name: Install Yarn Dependencies
        run: yarn --cwd web install --frozen-lockfile
      - name: Build Frontend
        run: yarn --cwd web build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: web/build
  build_go:
    needs:
      - build_react
    name: Build Backend
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64
            goopts: GOOS=linux GOARCH=amd64
          - name: linux-armv6
            goopts: GOOS=linux GOARCH=arm GOARM=6
    env:
      CGO_ENABLED: "0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.20'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: web/build
      - run: ${{ matrix.goopts }} go build -o ./keydrive ./main.go
      - run: chmod +x ./keydrive
      - uses: actions/upload-artifact@v2
        with:
          name: binary-${{ matrix.name }}
          path: ./keydrive
  build_docker:
    needs:
      - build_go
    name: Build Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: binary-linux-x64
          path: linux/amd64/keydrive
      - uses: actions/download-artifact@v2
        with:
          name: binary-linux-armv6
          path: linux/arm/v6/keydrive
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/keydrive/keydrive
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=main
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
